{% set name = "resolve-robotics-uri-py" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: be5b2c1eae3e61fa537f141f1320af47541bce2a58f8608bf50db28d4f660632

build:
  entry_points:
    - resolve-robotics-uri-py = resolve_robotics_uri_py.resolve_robotics_uri_py:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - wheel
    - setuptools >=45
    - setuptools-scm >=6.2
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - resolve_robotics_uri_py
  commands:
    - pip check
    - resolve-robotics-uri-py --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ami-iit/resolve-robotics-uri-py
  summary: Pure python package to solve ROS-style package:// and Gazebo-style model:// URIs in absolute paths.
  dev_url: https://github.com/ami-iit/resolve-robotics-uri-py
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - traversaro
