schema_version: 1

context:
  name: resolve-robotics-uri-py
  version: 0.3.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.io/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz
  sha256: be5b2c1eae3e61fa537f141f1320af47541bce2a58f8608bf50db28d4f660632

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv
  python:
    entry_points:
      - resolve-robotics-uri-py = resolve_robotics_uri_py.resolve_robotics_uri_py:main

requirements:
  host:
    - python >=3.8
    - wheel
    - setuptools >=45
    - setuptools-scm >=6.2
    - pip
  run:
    - python >=3.8

tests:
  - python:
      imports:
        - resolve_robotics_uri_py
      pip_check: true
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - pip
    script:
      - resolve-robotics-uri-py --help

about:
  summary: Pure python package to solve ROS-style package:// and Gazebo-style model:// URIs in absolute paths.
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://github.com/ami-iit/resolve-robotics-uri-py
  repository: https://github.com/ami-iit/resolve-robotics-uri-py

extra:
  recipe-maintainers:
    - traversaro
